name: Convert CSV to JSON

on:
  push:
    paths:
      - 'data/*.csv'
  workflow_dispatch:

jobs:
  convert-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas

      - name: Convert CSV to JSON
        run: |
          python -c "
import pandas as pd
df = pd.read_csv('data/model_catalog.csv')
df.to_json('data/model_catalog.json', orient='records', indent=2)
df = pd.read_csv('data/gpu_catalog.csv')
df.to_json('data/gpu_catalog.json', orient='records', indent=2)
"

      - name: Commit and push JSON files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data/*.json
          git commit -m 'Auto-convert CSV to JSON' || echo 'No changes to commit'
          git push